### PR TITLE
Adds support for lists of Polymorphic Embeds

### PR DESCRIPTION
**Pull request by jmnsf**
Split off #6

Adds support for lists of Polymorphic Embeds & docs to illustrate use.

### CODE REVIEW

**Comment by mathieuprog** [comment]
In the example code:
```
|> cast_polymorphic_embed(:channel)
|> cast_polymorphic_embed(:contexts)
```

How does PolymorphicEmbed type knows whether it's an array of embeds or not?

I also see this somewhere `default: []` as an option, I guess that was a mistake?

**Comment by jmnsf** [comment]
@mathieuprog Ecto tells us whether it's an array in the schema: https://github.com/mathieuprog/polymorphic_embed/pull/14/files#diff-a291756daff8ccac4fc17f41b7d86bf642ec4d582faa45035a9856cb79af6d23R281

**Comment by mathieuprog** [comment]
I should have a deeper look, but in `cast_polymorphic_embed` you call:
```
%{array?: array?, metadata: metadata, on_type_not_found: on_type_not_found} = get_options(changeset.data.__struct__, field)
```
But at that time you don't know if it's an array or not? How will you have the right value for `:array?`?
Because  `cast_polymorphic_embed` is called before `cast`.

**Comment by jmnsf** [comment]
Not according to the docs 🤔:
image

You need to have called `cast` in order to have a changeset in the first place. Maybe I'm missing something?

**Comment by mathieuprog** [comment]
yeah but not on the field `:channel`. It is `cast_polymorphic_embed` that will make the actual `cast` call for the field. I wonder why it works for you.

I think there's a mistake somewhere. Maybe the cardinality should be passed as an option, `[cardinality: :many]` that'd default to `:one`, or we need to remove `cast_polymorphic_embed` and change to `cast_polymorphic_embed_one` and `cast_polymorphic_embed_many` public functions. Or `cast_polymorphic_embed` and `cast_polymorphic_embeds` (singular vs plural).

It's a pity that the custom type is not automatically aware of that context data => array or not.

**Comment by jmnsf** [comment]
I think it works because ecto knows how to cast arrays, and it knows it's an array. You don't change your `cast` calls when the field is `:string` or `{:array, :string}` because ecto just works, the same holds here.

Happy to look into this given a failing test, as I'm not seeing the issue right now 🤔

**Comment by mathieuprog** [comment]
When I try to push on the branch
`git push git@github.com:myskoach/polymorphic_embed list-of-polymorphic-embeds`

It says
> ERROR: Permission to myskoach/polymorphic_embed.git denied to mathieuprog.

Can you check if edits from maintainers are allowed?
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

Checkbox "Allow edits from maintainers"

**Comment by mathieuprog** [comment]
Other quick question, shouldn't `:contexts` in the migration file be of type `{:array, :map}`, as we are storing a list of embeds?

**Comment by mathieuprog** [comment]
Never mind, just found the answer in the docs:

> It is recommended to declare your embeds_many/3 field with type :map in your migrations, instead of using {:array, :map}. Ecto can work with both maps and arrays as the container for embeds (and in most databases map are represented as JSON which allows Ecto to choose what works best).

**Comment by jmnsf** [comment]
@mathieuprog it's not there 🤷🏼‍♂️: 
image

Maybe send me a patch to _jf at skoach dot com_?

**Comment by paintingwithcode** [comment]
Hi, is there any update with this?

**Comment by mathieuprog** [comment]
It's coming, gotta find the time. Hope I'll get into this soon.

**Comment by mathieuprog** [comment]
@jmnsf @paintingwithcode  

Support for lists of embeds arrived in 1.1.0
Note that there is now a mandatory option to be set `:on_replace`.

@jmnsf I rewrote the code you provided as in the meanwhile there have been significant refactorings. I hope you don't mind. It is a very nice contribution!

**Pull request closed without merging**
