### PR TITLE
Don't create compile-time dependencies to embedded schemas

### LINKED ISSUE #85: Compile time dependencies between embedded schemas
When using `polymorphic_embeds_one` and `polymorphic_embeds_many` this library creates compile time dependencies between the parent module and the polymorphic embed modules. This causes huge dependency graphs in which changing a file requires a recompilation of many others.

This same problem existed in Ecto some time ago as reported in elixir-ecto/ecto#1610. The Ecto team fixed this by disabling the lexical tracker for the association modules as shown in elixir-ecto/ecto#1670.

Given that Polymorphic Embed aims to mimic Ecto's `embeds_one` and `embeds_many`. Would it make sense to use the same approach as Ecto did to fix this issue?

### PR DESCRIPTION
**Pull request by crbelaus**
When using `polymorphic_embeds_one` or `polymorphic_embeds_many` we create compile-time dependencies from the parent schema to the embedded schemas.

For example, let's say we have the following code:

```elixir
# lib/article.ex
defmodule Article do
  use Ecto.Schema

  import PolymorphicEmbed

  embedded_schema do
    polymorphic_embeds_many :thing,
      types: [comment: Comment, reaction: Reaction],
      on_replace: :delete
  end
end

# lib/comment.ex
defmodule Comment do
  use Ecto.Schema

  embedded_schema do
    field :content, :string
  end
end

# lib/reaction.ex
defmodule Reaction do
  use Ecto.Schema

  embedded_schema do
    field :content, :string
  end
end
```

This provides the following output. As we can see, the `Article` schema has a compile-time dependency on the `Comment` and `Reaction` schemas:

```
mix xref graph --source lib/article.ex --label compile

lib/article.ex
├── lib/comment.ex (compile)
├── lib/polymorphic_embed.ex (compile)
└── lib/reaction.ex (compile)
```

Ecto had this same issue early on with associations. In particular with `embeds_one` and `embeds_many`. They solved it by expanding the aliases and disabling the lexical tracker for associated schemas as shown in elixir-ecto/ecto#1670.

This pull request applies the same solution. This is safe since we don't call any functions in the associated schemas. The result is that running the previous command shows that there are no compile-time dependencies anymore. 

```
mix xref graph --source lib/article.ex --label compile

lib/article.ex
└── lib/polymorphic_embed.ex (compile)
```

Closes #85

### CODE REVIEW

**Comment by doughsay** [comment]
Hey there, we very much would like to use this library at work, but we use this in our CI:

```
mix xref graph --label compile-connected --fail-above 0
```

so any usage of polymorphic embed fails.  Would really appreciate it if we could get this PR merged and released!  Thanks! ❤️

**Comment by mathieuprog** [comment]
I merged this on master however there are 2 test failures right now

**Comment by mathieuprog** [comment]
@crbelaus @doughsay 

I have to revert this as it leads to side-effects and 2 test failures.

Take the test `"form with polymorphic embed to nil"`
An `IO.inspect` of the nested form for the `:channel`:
```elixir
        contents =
          safe_inputs_for(changeset, :channel, generator, fn f ->
            IO.inspect f
```

will output the following:
```elixir
%Phoenix.HTML.Form{
  source: #Ecto.Changeset<
    action: nil,
    changes: %{},
    errors: [
      number: {"can't be blank", [validation: :required]},
      country_code: {"can't be blank", [validation: :required]},
      provider: {"can't be blank", [validation: :required]}
    ],
    data: #PolymorphicEmbed.Regular.Channel.SMS<>,
    valid?: false
  >,
  impl: Phoenix.HTML.FormData.Ecto.Changeset,
  id: "reminder_channel",
  name: "reminder[channel]",
  data: %PolymorphicEmbed.Regular.Channel.SMS{
    id: nil,
    number: nil,
    country_code: nil,
    custom: false,
    provider: nil,
    result: nil,
    attempts: []
  },
  action: :insert,
  hidden: [],
  params: %{},
  errors: [
    number: {"can't be blank", [validation: :required]},
    country_code: {"can't be blank", [validation: :required]},
    provider: {"can't be blank", [validation: :required]}
  ],
  options: [],
  index: nil
}
```

Expected output:
```elixir
%Phoenix.HTML.Form{
  source: #Ecto.Changeset<
    action: nil,
    changes: %{},
    errors: [
      number: {"can't be blank", [validation: :required]},
      country_code: {"can't be blank", [validation: :required]},
      provider: {"can't be blank", [validation: :required]}
    ],
    data: #PolymorphicEmbed.Regular.Channel.SMS<>,
    valid?: false
  >,
  impl: Phoenix.HTML.FormData.Ecto.Changeset,
  id: "reminder_channel",
  name: "reminder[channel]",
  data: %PolymorphicEmbed.Regular.Channel.SMS{
    id: nil,
    number: nil,
    country_code: nil,
    custom: false,
    provider: nil,
    result: nil,
    attempts: []
  },
  hidden: [],
  params: %{},
  errors: [],
  options: [],
  index: nil
}
```

Note that the expected output is right as it follows the default behavior for `embeds_one`/`embeds_many` in Ecto.

**Comment by mathieuprog** [comment]
Also this code is a little too meta for me, as I have a long list of tasks to complete. If you could look as to why there are these side effects, I'll merge as soon as the tests pass.

**Comment by mathieuprog** [comment]
I actually found out the tests fail because of the `mix.lock` update, not the expanding of aliases. Specifically:
```
  ecto 3.11.1 => 3.11.2
  phoenix_ecto 4.4.3 => 4.6.1
 ```

**Comment by mathieuprog** [comment]
This has been released in `3.0.7`. Note that I had to add an additional clause in the case the types are indirectly referenced through a module attribute.

https://github.com/mathieuprog/polymorphic_embed/blob/v.3.0.7/lib/polymorphic_embed.ex#L46

**Comment by crbelaus** [comment]
Honestly I am not sure @mathieuprog. My understanding of how to handle those compile time dependencies is not that deep.

We may need to ask someone from the Ecto core team and see if they have any insights as they have more experience handling this kind of dependencies (my initial PR was an adaptation of Ecto's own changes).

**Pull request merged**
