### PR TITLE
Fix Form Regression

### LINKED ISSUE #30: Regression for Form
This commit introduces a regression for me: https://github.com/mathieuprog/polymorphic_embed/commit/0081ac2cef2b2dc2df354f1f43d5b3b93ae5f9fd

Installed Version: `1.3.3`

The `to_form` function only works for me if the changeset is invalid, as soon as it is valid, I get an `ArgumentError`:

```
[error] GenServer #PID<0.1829.0> terminating
** (FunctionClauseError) no function clause matching in PolymorphicEmbed.HTML.Form.do_get_errors/1
    (polymorphic_embed 1.3.3) lib/html/form.ex:70: PolymorphicEmbed.HTML.Form.do_get_errors(%Acme.CaseContext.ProtocolEntry.Sms{delivery_receipt_id: nil, text: "f", uuid: nil})
    (polymorphic_embed 1.3.3) lib/html/form.ex:26: PolymorphicEmbed.HTML.Form.to_form/5
    (acme_web 0.0.0-noversion) lib/acme_web/live/polymorphic_inputs.ex:20: anonymous fn/4 in AcmeWeb.PolimorphicInputs.render/1
    (phoenix_live_view 0.15.3) lib/phoenix_live_view/diff.ex:342: Phoenix.LiveView.Diff.traverse/6
    (phoenix_live_view 0.15.3) lib/phoenix_live_view/diff.ex:430: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/6
    (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.15.3) lib/phoenix_live_view/diff.ex:342: Phoenix.LiveView.Diff.traverse/6
    (phoenix_live_view 0.15.3) lib/phoenix_live_view/diff.ex:430: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/6
    (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.15.3) lib/phoenix_live_view/diff.ex:342: Phoenix.LiveView.Diff.traverse/6
    (phoenix_live_view 0.15.3) lib/phoenix_live_view/diff.ex:430: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/6
    (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.15.3) lib/phoenix_live_view/diff.ex:342: Phoenix.LiveView.Diff.traverse/6
    (phoenix_live_view 0.15.3) lib/phoenix_live_view/diff.ex:430: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/6
    (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix_live_view 0.15.3) lib/phoenix_live_view/diff.ex:342: Phoenix.LiveView.Diff.traverse/6
    (phoenix_live_view 0.15.3) lib/phoenix_live_view/diff.ex:584: Phoenix.LiveView.Diff.render_component/9
    (phoenix_live_view 0.15.3) lib/phoenix_live_view/diff.ex:529: anonymous fn/5 in Phoenix.LiveView.Diff.render_pending_components/6
    (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
    (stdlib 3.13.2) maps.erl:233: :maps.fold_1/3

```

Changeset at time of error:

```elixir
#Ecto.Changeset<
  action: :validate,
  changes: %{
    entry: %Acme.CaseContext.ProtocolEntry.Sms{
      delivery_receipt_id: nil,
      text: "f",
      uuid: nil
    },
    type: "sms"
  },
  errors: [],
  data: #Acme.CaseContext.ProtocolEntry<>,
  valid?: true
>
```

Changeset when working:

```elixir
#Ecto.Changeset<
  action: :validate,
  changes: %{
    entry: #Ecto.Changeset<
      action: :insert,
      changes: %{text: "fffffffffffffffffffffffff"},
      errors: [delivery_receipt_id: {"can't be blank", [validation: :required]}],
      data: #Hygeia.CaseContext.ProtocolEntry.Sms<>,
      valid?: false
    >,
    type: "sms"
  },
  errors: [],
  data: #Hygeia.CaseContext.ProtocolEntry<>,
  valid?: false
>
```

### PR DESCRIPTION
**Pull request by maennchen**
Fixes #30
Merge #31 first

### CODE REVIEW

**Comment by maennchen** [comment]
@mathieuprog I'll try to put together a test as well.

**Comment by mathieuprog** [comment]
Didn't have a deep look yet but I'm very curious to see the test case. I worked on this a lot, works perfectly for me. Maybe you use the form in a way I didn't expect.

**Comment by mathieuprog** [comment]
FYI the lignes `for polymorphic? <- [false, true] do` is because I want to perform the test without the polymorphic (just using `embeds_one`/`embeds_many`) and then with polymorphy, to ensure the result is the same for both versions.

**Comment by maennchen** [comment]
@mathieuprog Found a case that illustrates it nicely.

**Comment by maennchen** [comment]
@mathieuprog Rebased.

**Comment by mathieuprog** [comment]
Actually it also fails for an insert. So the test should renamed.
`test "inputs_for/4 after insert" do` should be renamed to 
`test "inputs_for/4 after invalid insert" do`

and your test `test "inputs_for/4 after invalid update" do` should be renamed to
`test "inputs_for/4 after invalid insert with valid nested struct" do`

**Comment by mathieuprog** [comment]
Also I think it's better to do pattern matching on a Changeset, instead of wrapping the struct by a Changeset.

The `do_get_errors` can pattern match on a Changeset. If no changeset it can return `[]`.

**Comment by maennchen** [comment]
@mathieuprog Done.

**Comment by mathieuprog** [comment]
I like that you wrote  `_schema` :)

**Comment by maennchen** [comment]
@mathieuprog In all my projects I have a Credo rule enforcing never to write just `_`. It forces me to name the things I do not care about and makes it a lot more readable for other people.

**Pull request merged**
